GET http://localhost:4000/
###
GET http://localhost:4000/status
###
GET http://localhost:4000/blocks
###
POST http://localhost:4000/blocks
###
GET http://localhost:4000/blocks/2
###
GET http://localhost:4000/balance/winter
###
GET http://localhost:4000/balance/e5737b17850f22a074586ac3b980f46936a35d8f68f963ba3e6e1c383d353618298580c80148df7b6ef4b980d9649fa0019c62e72824d9c8edb806ee9d3a1913
###
GET http://localhost:4000/mempool
###
POST http://localhost:4000/transactions

{
  "to": "winter",
  "amount": 40
}
###
POST http://localhost:4000/peers

{
  "address": "127.0.0.1",
  "port": "3000"
}