GET http://localhost:4000/
###
GET http://localhost:3000/status
###
GET http://localhost:3003/blocks
###
POST http://localhost:3000/blocks
###
GET http://localhost:4000/blocks/2
###
GET http://localhost:4000/balance
###
GET http://localhost:4000/balance/c5db43a4743e7f7ac9254783840d0e83180a3b62c308f319cb734d92a2f0c019a49efe225b9131545bcd64c086eb80962dafe80a9552070a8610fb736e940795?total=true
###
GET http://localhost:3000/mempool
###
POST http://localhost:3000/transactions

{
  "to": "winter",
  "amount": 10
}
###
POST http://localhost:3002/peers

{
  "address": "127.0.0.1",
  "port": "3003"
}
###
GET http://localhost:3000/peers